### ISSUE TITLE
Does this work on yi-hack-Allwinner-v2?

### ISSUE THREAD

**Issue by keanpogi** [cheese1/yi-hack-MStar-rsync#1]
Hi there, I would like to ask if this system works for https://github.com/roleoroleo/yi-hack-Allwinner-v2 also?

Thank you

**Comment by cheese1** [comment]
i have no cam running allwinner-v2
but you could give it a try and get back with info, their *should* be no harm. if it would not work just delete the binary.

**Comment by keanpogi** [comment]
Thank you sir

**Comment by cheese1** [comment]
welcome
