### ISSUE TITLE
sh: rsync: not found

### ISSUE THREAD

**Issue by meskilla** [cheese1/yi-hack-MStar-rsync#2]
`rsync -naP root@yi-hack:/tmp/sd/record/ ~/Downloads/`

rsync is stored in /tmp/sd/bin/ which is part of $PATH.

I know I'm trying the opposite of what you suggested, but this usually works fine on my linux servers.

Can't the yi-hack rsync act as the rsync server?
Could it run in daemon mode and respond to outside requests?

**Comment by cheese1** [comment]
works for me, you need to set the full path to the location of rsync as follows:

rsync is under /tmp/sd/yi-hack/bin/rsync 

~~~
[cheese@localhost source]$ rsync --rsync-path=/tmp/sd/yi-hack/bin/rsync -avp /tmp/source/ root@192.168.89.97:/tmp/abc/
root@192.168.89.97's password: 
sending incremental file list
created directory /tmp/abc
./
a

sent 117 bytes  received 69 bytes  53.14 bytes/sec
total size is 0  speedup is 0.00
~~~
